# config/services/brevo.yaml
# Brevo (formerly Sendinblue) Email Marketing API Service Configuration
name: "brevo"
display_name: "Brevo Email Marketing"
description: "Email marketing, transactional emails, SMS, and WhatsApp Business API"
version: "v3"
base_url: "https://api.brevo.com/v3"
documentation_url: "https://developers.brevo.com/docs"

# Authentication methods supported by Brevo
authentication:
  api_key:
    type: "api_key"
    header: "api-key"
    description: "Brevo API key from account settings"
    required_fields: ["api_key"]

# Rate limiting configuration (Brevo's limits)
rate_limits:
  requests_per_minute: 300
  requests_per_hour: 10000
  burst_limit: 50
  concurrent_requests: 10

# Brevo API endpoints
endpoints:
  # Account information
  get_account:
    method: "GET"
    path: "/account"
    description: "Get account information and plan details"

  # Contact management
  list_contacts:
    method: "GET"
    path: "/contacts"
    description: "Get all contacts"
    optional_params: ["limit", "offset", "modifiedSince", "sort"]

  create_contact:
    method: "POST"
    path: "/contacts"
    description: "Create a new contact"
    required_params: ["email"]
    optional_params: ["attributes", "listIds", "updateEnabled"]

  get_contact:
    method: "GET"
    path: "/contacts/{identifier}"
    description: "Get contact information"
    required_params: ["identifier"]

  update_contact:
    method: "PUT"
    path: "/contacts/{identifier}"
    description: "Update a contact"
    required_params: ["identifier"]
    optional_params: ["attributes", "listIds"]

  delete_contact:
    method: "DELETE"
    path: "/contacts/{identifier}"
    description: "Delete a contact"
    required_params: ["identifier"]

  # Contact lists
  list_contact_lists:
    method: "GET"
    path: "/contacts/lists"
    description: "Get all contact lists"
    optional_params: ["limit", "offset", "sort"]

  create_contact_list:
    method: "POST"
    path: "/contacts/lists"
    description: "Create a contact list"
    required_params: ["name"]
    optional_params: ["folderId"]

  get_contact_list:
    method: "GET"
    path: "/contacts/lists/{listId}"
    description: "Get a contact list"
    required_params: ["listId"]

  # Email campaigns
  list_email_campaigns:
    method: "GET"
    path: "/emailCampaigns"
    description: "Get all email campaigns"
    optional_params: ["type", "status", "limit", "offset"]

  create_email_campaign:
    method: "POST"
    path: "/emailCampaigns"
    description: "Create an email campaign"
    required_params: ["name", "subject", "sender", "recipients"]
    optional_params: ["htmlContent", "textContent", "scheduledAt"]

  get_email_campaign:
    method: "GET"
    path: "/emailCampaigns/{campaignId}"
    description: "Get an email campaign"
    required_params: ["campaignId"]

  send_email_campaign:
    method: "POST"
    path: "/emailCampaigns/{campaignId}/sendNow"
    description: "Send an email campaign immediately"
    required_params: ["campaignId"]

  # Transactional emails
  send_transactional_email:
    method: "POST"
    path: "/smtp/email"
    description: "Send a transactional email"
    required_params: ["to"]
    optional_params:
      [
        "sender",
        "subject",
        "htmlContent",
        "textContent",
        "templateId",
        "params"
      ]

  list_email_templates:
    method: "GET"
    path: "/smtp/templates"
    description: "Get all email templates"
    optional_params: ["templateStatus", "limit", "offset"]

  create_email_template:
    method: "POST"
    path: "/smtp/templates"
    description: "Create an email template"
    required_params: ["templateName", "htmlContent", "subject", "sender"]
    optional_params: ["textContent", "tag", "isActive"]

  # SMS campaigns
  list_sms_campaigns:
    method: "GET"
    path: "/smsCampaigns"
    description: "Get all SMS campaigns"
    optional_params: ["status", "limit", "offset"]

  create_sms_campaign:
    method: "POST"
    path: "/smsCampaigns"
    description: "Create an SMS campaign"
    required_params: ["name", "sender", "content", "recipients"]
    optional_params: ["scheduledAt"]

  send_transactional_sms:
    method: "POST"
    path: "/transactionalSMS/sms"
    description: "Send a transactional SMS"
    required_params: ["sender", "recipient", "content"]
    optional_params: ["type", "tag"]

  # WhatsApp
  send_whatsapp_message:
    method: "POST"
    path: "/whatsapp/sendMessage"
    description: "Send a WhatsApp message"
    required_params: ["to", "type"]
    optional_params:
      ["text", "image", "document", "templateName", "templateLanguage"]

  # Email statistics
  get_email_statistics:
    method: "GET"
    path: "/emailCampaigns/{campaignId}/statistics"
    description: "Get email campaign statistics"
    required_params: ["campaignId"]

  get_email_events:
    method: "GET"
    path: "/emailCampaigns/{campaignId}/events"
    description: "Get email campaign events"
    required_params: ["campaignId"]
    optional_params: ["limit", "offset", "event"]

  # Global statistics
  get_email_activity:
    method: "GET"
    path: "/emailActivity"
    description: "Get global email activity statistics"
    optional_params: ["startDate", "endDate", "days", "tag"]

# Webhook configuration
webhooks:
  supported: true
  events:
    - "delivered"
    - "hardBounce"
    - "softBounce"
    - "blocked"
    - "spam"
    - "unsubscribed"
    - "clicked"
    - "opened"
    - "invalid"
    - "deferred"
    - "request"
    - "uniqueOpened"
    - "complaint"
    - "listAddition"
    - "contactUpdated"
    - "contactDeleted"
  signature_header: "X-Brevo-Signature"
  verification_method: "hmac_sha256"

# Environment configurations
environments:
  production:
    base_url: "https://api.brevo.com/v3"
    description: "Brevo production environment"

  # Note: Brevo doesn't have a separate sandbox, but has a test mode
  development:
    base_url: "https://api.brevo.com/v3"
    description: "Brevo production API (use test email addresses for testing)"
    rate_limits:
      requests_per_minute: 100 # Lower limits for development

# Additional Brevo-specific settings
settings:
  timeout: 30
  retries: 3
  verify_ssl: true
  default_sender_email: "${BREVO_DEFAULT_SENDER_EMAIL:noreply@yourdomain.com}"
  default_sender_name: "${BREVO_DEFAULT_SENDER_NAME:API Testing Platform}"
  enable_tracking: true # Enable open and click tracking
  enable_batch_processing: true # For bulk operations
