services:
  brevo:
    enabled: true
    config_file: "brevo.yaml"
    description: "Brevo email marketing and communication API"
    category: "marketing"

  # linkedin:
  #   enabled: false
  #   config_file: "linkedin.yaml"
  #   description: "LinkedIn professional networking API"
  #   category: "social"

  # n8n:
  #   enabled: false
  #   config_file: "n8n.yaml"
  #   description: "n8n workflow automation API"
  #   category: "automation"

  # slack:
  #   enabled: false
  #   config_file: "slack.yaml"
  #   description: "Slack team communication API"
  #   category: "communication"

# Global settings
global_settings:
  default_timeout: 30
  default_retries: 3
  max_concurrent_requests: 10
  rate_limit_strategy: "sliding_window"

# Development settings
development:
  auto_reload_configs: true
  verbose_logging: true
  mock_external_calls: false
